export { default as Header } from "./Header/Header";
export { default as Footer } from "./Footer/Footer";
export { default as Home } from "./Home/Home";
export { default as Recipes } from "./Recipes/Recipes";
export { default as MealDetails } from "./MealDetails/MealDetails";
export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
// export { default as Search } from "./Search";
